#!/bin/bash

# version 0.1
#
# wget https://raw.githubusercontent.com/western/vpnset/dev/dnscrypt_proxy_opt && chmod +x dnscrypt_proxy_opt
#
#

function main {
    
    notice "start main"
    
    
    dnscrypt_proxy_opt
}



# ------------------------------------------------------------------------------



function dnscrypt_proxy_opt {

    notice "dnscrypt_proxy opt install"

    if ! whoami | grep -q root; then
        err 'root required. exit.'
    fi


    pushd /opt/
        wget https://github.com/DNSCrypt/dnscrypt-proxy/releases/download/2.1.15/dnscrypt-proxy-linux_x86_64-2.1.15.tar.gz
        tar xf dnscrypt-proxy-linux_x86_64-2.1.15.tar.gz --transform s/linux-x86_64/dnscrypt-proxy/
    popd

    mkdir -p /etc/dnscrypt-proxy /var/log/dnscrypt-proxy


    pushd /etc/dnscrypt-proxy
        wget https://raw.githubusercontent.com/western/vpnset/dev/dnscrypt-proxy.toml
    popd


    pushd /lib/systemd/system/
        wget https://raw.githubusercontent.com/western/vpnset/dev/dnscrypt-proxy.service
        ln -s /lib/systemd/system/dnscrypt-proxy.service /etc/systemd/system/multi-user.target.wants/
    popd



    systemctl daemon-reload ; systemctl restart dnscrypt-proxy.service

}


# ------------------------------------------------------------------------------



# ------------------------------------------------------------------------------

function notice {
    builtin echo -en "\033[1m"
    echo "NOTICE: $@"
    builtin echo -en "\033[0m"
}

function success {
    builtin echo -en "\033[1;32m"
    echo "SUCCESS: $@"
    builtin echo -en "\033[0m"
}

function warn {
    builtin echo -en "\033[1;33m"
    echo "WARN: $@"
    builtin echo -en "\033[0m"
}

function err {
    builtin echo -en "\033[1;31m"
    echo "ERR: $@"
    builtin echo -en "\033[0m"
    exit 1
}

function fatal {
    builtin echo -en "\033[1;31m"
    echo "FATAL: $@"
    builtin echo -en "\033[0m"
    exit 1
}

# ------------------------------------------------------------------------------

main


