#!/bin/bash

# version 0.1
#
# wget https://raw.githubusercontent.com/western/vpnset/dev/init && chmod +x init
#
#

function main {
    
    notice "start init"
    
    
    root_prepare
}



# ------------------------------------------------------------------------------


function root_prepare {

    notice "root_prepare"

    if ! whoami | grep -q root; then
        err 'root required. exit.'
    fi
    
    pushd /root/
        wget https://raw.githubusercontent.com/western/vpnset/dev/.vimrc
        wget https://raw.githubusercontent.com/western/vpnset/dev/.alias
        echo "" >> .bashrc
        echo "source .alias" >> .bashrc
        source /root/.alias
    popd
    
    
    # ------------------------------------------------------------------------------
    
    
    if cat /etc/*release* | grep -q 'VERSION="13 (trixie)"'; then
        warn 'Debian 13 detected.'
        apt-get update && apt-get upgrade -u
        apt-get install -y vim mc less lsof plocate git curl wget aptitude easy-rsa
        apt-get install -y iptables iptables-persistent wireguard 
        #apt-get remove -y zabbix-agent-timeweb

        # debian13 dnscrypt-proxy setup
        
        
        #apt-get install -y dnscrypt-proxy
        #systemctl disable systemd-resolved
        #systemctl stop systemd-resolved
        
    fi
    
    if cat /etc/*release* | grep -q 'VERSION="12 (bookworm)"'; then
        warn 'Debian 12 detected.'
        apt-get update && apt-get upgrade -u
        apt-get install -y vim mc less lsof mlocate git curl wget aptitude easy-rsa
        apt-get install -y iptables iptables-persistent wireguard
        #apt-get remove -y zabbix-agent-timeweb

        # debian12 do not contain dnscrypt-proxy
        # run dnscrypt_proxy_opt
        #dnscrypt_proxy_opt
    fi


    if cat /etc/*release* | grep -q 'VERSION="11 (bullseye)"'; then
        warn 'Debian 11 detected.'
        apt-get update && apt-get upgrade -u
        apt-get install -y vim mc less lsof mlocate git curl wget aptitude easy-rsa
        apt-get install -y iptables iptables-persistent wireguard
        #apt-get remove -y zabbix-agent-timeweb

        # debian11
        # run dnscrypt_proxy_opt from scratch
        #dnscrypt_proxy_opt
    fi


    


    local SYSCTL="/etc/sysctl.conf"
    echo "" >> $SYSCTL
    echo "net.ipv4.ip_forward = 1" >> $SYSCTL
    #echo "net.ipv4.icmp_echo_ignore_all = 1" >> $SYSCTL
    sysctl -p


    # show
    #iptables -L -vn -t nat

    # all reset
    iptables -F
    iptables -X
    iptables -t nat -F
    iptables -t nat -X

    # set
    iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE


    # iptables-persistent
    /sbin/iptables-save > /etc/iptables/rules.v4


    
    #dnscrypt_proxy_configure
    
    
}


# ------------------------------------------------------------------------------



# ------------------------------------------------------------------------------

function notice {
    builtin echo -en "\033[1m"
    echo "NOTICE: $@"
    builtin echo -en "\033[0m"
}

function success {
    builtin echo -en "\033[1;32m"
    echo "SUCCESS: $@"
    builtin echo -en "\033[0m"
}

function warn {
    builtin echo -en "\033[1;33m"
    echo "WARN: $@"
    builtin echo -en "\033[0m"
}

function err {
    builtin echo -en "\033[1;31m"
    echo "ERR: $@"
    builtin echo -en "\033[0m"
    exit 1
}

function fatal {
    builtin echo -en "\033[1;31m"
    echo "FATAL: $@"
    builtin echo -en "\033[0m"
    exit 1
}

# ------------------------------------------------------------------------------

main

